# Generated by Django 4.2.24 on 2025-09-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_cores_product_image_product_ram_and_more'),
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinquiry',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='productinquiry',
            name='product',
        ),
        migrations.AddField(
            model_name='productinquiry',
            name='products',
            field=models.ManyToManyField(related_name='inquiries', to='product.product'),
        ),
    ]
