# Generated by Django 4.2.24 on 2025-09-24 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('inquiries', '0002_remove_productinquiry_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinquiry',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.cart'),
        ),
    ]
