--
-- PostgreSQL database dump
--

\restrict lvzkCK1OSwqgmhcLxnLiz1J7dqXBbJ8gg5sq6JMj7lofOaCQgDAIyQVFg9JB4wc

-- Dumped from database version 14.18 (Homebrew)
-- Dumped by pg_dump version 14.20 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: account_passwordresetotp; Type: TABLE; Schema: public; Owner: tungstonlabs
--

CREATE TABLE public.account_passwordresetotp (
    id uuid NOT NULL,
    otp character varying(5) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    is_used boolean NOT NULL,
    user_id uuid NOT NULL
);


ALTER TABLE public.account_passwordresetotp OWNER TO tungstonlabs;

--
-- Name: account_user; Type: TABLE; Schema: public; Owner: tungstonlabs
--

CREATE TABLE public.account_user (
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    id uuid NOT NULL,
    email character varying(255) NOT NULL,
    is_active boolean NOT NULL,
    is_admin boolean NOT NULL,
    is_staff boolean NOT NULL
);


ALTER TABLE public.account_user OWNER TO tungstonlabs;

--
-- Name: account_user_groups; Type: TABLE; Schema: public; Owner: tungstonlabs
--

CREATE TABLE public.account_user_groups (
    id bigint NOT NULL,
    user_id uuid NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.account_user_groups OWNER TO tungstonlabs;

--
-- Name: account_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: tungstonlabs
--

ALTER TABLE public.account_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: account_user_user_permissions; Type: TABLE; Schema: public; Owner: tungstonlabs
--

CREATE TABLE public.account_user_user_permissions (
    id bigint NOT NULL,
    user_id uuid NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.account_user_user_permissions OWNER TO tungstonlabs;

--
-- Name: account_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: tungstonlabs
--

ALTER TABLE public.account_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: tungstonlabs
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO tungstonlabs;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: tungstonlabs
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: tungstonlabs
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO tungstonlabs;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: tungstonlabs
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: tungstonlabs
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO tungstonlabs;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: tungstonlabs
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cart_cart; Type: TABLE; Schema: public; Owner: tungstonlabs
--

CREATE TABLE public.cart_cart (
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    id uuid NOT NULL,
    cart_token character varying(100),
    checked_out boolean NOT NULL,
    user_id uuid
);


ALTER TABLE public.cart_cart OWNER TO tungstonlabs;

--
-- Name: cart_cartitem; Type: TABLE; Schema: public; Owner: tungstonlabs
--

CREATE TABLE public.cart_cartitem (
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    id uuid NOT NULL,
    quantity integer NOT NULL,
    price_at_add numeric(12,2) NOT NULL,
    cart_id uuid NOT NULL,
    product_id bigint NOT NULL,
    CONSTRAINT cart_cartitem_quantity_check CHECK ((quantity >= 0))
);


ALTER TABLE public.cart_cartitem OWNER TO tungstonlabs;

--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: tungstonlabs
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id uuid NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO tungstonlabs;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: tungstonlabs
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: tungstonlabs
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO tungstonlabs;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: tungstonlabs
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: tungstonlabs
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO tungstonlabs;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: tungstonlabs
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: tungstonlabs
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO tungstonlabs;

--
-- Name: inquiries_productinquiry; Type: TABLE; Schema: public; Owner: tungstonlabs
--

CREATE TABLE public.inquiries_productinquiry (
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    id uuid NOT NULL,
    first_name character varying(120) NOT NULL,
    last_name character varying(120),
    company_name character varying(250),
    email character varying(254) NOT NULL,
    phone character varying(50),
    address text,
    country character varying(120),
    state character varying(120),
    delivery_location text,
    description text,
    status character varying(20) NOT NULL,
    cart_id uuid
);


ALTER TABLE public.inquiries_productinquiry OWNER TO tungstonlabs;

--
-- Name: inquiries_productinquiry_products; Type: TABLE; Schema: public; Owner: tungstonlabs
--

CREATE TABLE public.inquiries_productinquiry_products (
    id bigint NOT NULL,
    productinquiry_id uuid NOT NULL,
    product_id bigint NOT NULL
);


ALTER TABLE public.inquiries_productinquiry_products OWNER TO tungstonlabs;

--
-- Name: inquiries_productinquiry_products_id_seq; Type: SEQUENCE; Schema: public; Owner: tungstonlabs
--

ALTER TABLE public.inquiries_productinquiry_products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inquiries_productinquiry_products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_board; Type: TABLE; Schema: public; Owner: tungstonlabs
--

CREATE TABLE public.product_board (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    slug character varying(100) NOT NULL,
    name character varying(150) NOT NULL,
    short_tagline character varying(255) NOT NULL,
    dram_config character varying(150) NOT NULL,
    emmc_config character varying(150) NOT NULL,
    storage_slots character varying(200) NOT NULL,
    wifi character varying(150) NOT NULL,
    ethernet character varying(200) NOT NULL,
    video_connectors character varying(200) NOT NULL,
    expansion character varying(200) NOT NULL,
    gpio_headers character varying(200) NOT NULL,
    power_input character varying(150) NOT NULL,
    form_factor character varying(150) NOT NULL,
    additional_info jsonb,
    is_active boolean NOT NULL,
    image character varying(100),
    processor_id bigint NOT NULL
);


ALTER TABLE public.product_board OWNER TO tungstonlabs;

--
-- Name: product_board_id_seq; Type: SEQUENCE; Schema: public; Owner: tungstonlabs
--

ALTER TABLE public.product_board ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_board_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_category; Type: TABLE; Schema: public; Owner: tungstonlabs
--

CREATE TABLE public.product_category (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    name character varying(100) NOT NULL
);


ALTER TABLE public.product_category OWNER TO tungstonlabs;

--
-- Name: product_category_id_seq; Type: SEQUENCE; Schema: public; Owner: tungstonlabs
--

ALTER TABLE public.product_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_processor; Type: TABLE; Schema: public; Owner: tungstonlabs
--

CREATE TABLE public.product_processor (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(100) NOT NULL,
    cpu_cores integer,
    cpu_arch character varying(100) NOT NULL,
    arch_bits character varying,
    l1_cache_kb character varying,
    l2_cache_kb character varying,
    gpu character varying(100) NOT NULL,
    npu_tops numeric(5,2),
    max_dram_gb character varying,
    hdmi boolean NOT NULL,
    lvds boolean NOT NULL,
    edp boolean NOT NULL,
    dp boolean NOT NULL,
    mipi_dsi boolean NOT NULL,
    usb2_ports character varying,
    usb3_ports character varying,
    pcie_desc character varying(100) NOT NULL,
    ethernet_cap character varying(100) NOT NULL,
    sata boolean NOT NULL,
    sdio boolean NOT NULL,
    extra jsonb,
    image character varying(100),
    vendor_id bigint NOT NULL,
    CONSTRAINT product_processor_cpu_cores_check CHECK ((cpu_cores >= 0))
);


ALTER TABLE public.product_processor OWNER TO tungstonlabs;

--
-- Name: product_processor_id_seq; Type: SEQUENCE; Schema: public; Owner: tungstonlabs
--

ALTER TABLE public.product_processor ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_processor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_product; Type: TABLE; Schema: public; Owner: tungstonlabs
--

CREATE TABLE public.product_product (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    name character varying(150) NOT NULL,
    ram_gb integer NOT NULL,
    ram_expandable_upto integer,
    storage character varying(100) NOT NULL,
    price numeric(10,2) NOT NULL,
    image character varying(100),
    available boolean NOT NULL,
    board_id bigint,
    processor_id bigint,
    CONSTRAINT product_product_ram_expandable_upto_check CHECK ((ram_expandable_upto >= 0)),
    CONSTRAINT product_product_ram_gb_check CHECK ((ram_gb >= 0))
);


ALTER TABLE public.product_product OWNER TO tungstonlabs;

--
-- Name: product_product_id_seq; Type: SEQUENCE; Schema: public; Owner: tungstonlabs
--

ALTER TABLE public.product_product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_vendor; Type: TABLE; Schema: public; Owner: tungstonlabs
--

CREATE TABLE public.product_vendor (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    name character varying(100) NOT NULL,
    category_id bigint NOT NULL,
    image character varying(100),
    description text,
    website_url character varying(200)
);


ALTER TABLE public.product_vendor OWNER TO tungstonlabs;

--
-- Name: product_vendor_id_seq; Type: SEQUENCE; Schema: public; Owner: tungstonlabs
--

ALTER TABLE public.product_vendor ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_vendor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: review_review; Type: TABLE; Schema: public; Owner: tungstonlabs
--

CREATE TABLE public.review_review (
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    id uuid NOT NULL,
    name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    rating smallint NOT NULL,
    review text,
    approved boolean NOT NULL,
    product_id bigint NOT NULL,
    CONSTRAINT review_review_rating_check CHECK ((rating >= 0))
);


ALTER TABLE public.review_review OWNER TO tungstonlabs;

--
-- Name: token_blacklist_blacklistedtoken; Type: TABLE; Schema: public; Owner: tungstonlabs
--

CREATE TABLE public.token_blacklist_blacklistedtoken (
    id bigint NOT NULL,
    blacklisted_at timestamp with time zone NOT NULL,
    token_id bigint NOT NULL
);


ALTER TABLE public.token_blacklist_blacklistedtoken OWNER TO tungstonlabs;

--
-- Name: token_blacklist_blacklistedtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: tungstonlabs
--

ALTER TABLE public.token_blacklist_blacklistedtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_blacklistedtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: token_blacklist_outstandingtoken; Type: TABLE; Schema: public; Owner: tungstonlabs
--

CREATE TABLE public.token_blacklist_outstandingtoken (
    id bigint NOT NULL,
    token text NOT NULL,
    created_at timestamp with time zone,
    expires_at timestamp with time zone NOT NULL,
    user_id uuid,
    jti character varying(255) NOT NULL
);


ALTER TABLE public.token_blacklist_outstandingtoken OWNER TO tungstonlabs;

--
-- Name: token_blacklist_outstandingtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: tungstonlabs
--

ALTER TABLE public.token_blacklist_outstandingtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_outstandingtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: account_passwordresetotp; Type: TABLE DATA; Schema: public; Owner: tungstonlabs
--

COPY public.account_passwordresetotp (id, otp, created_at, is_used, user_id) FROM stdin;
\.


--
-- Data for Name: account_user; Type: TABLE DATA; Schema: public; Owner: tungstonlabs
--

COPY public.account_user (password, last_login, is_superuser, id, email, is_active, is_admin, is_staff) FROM stdin;
pbkdf2_sha256$600000$2710CVBGC3vGw9Zs9THVBQ$g5IifLUTcBYpN80fuql5hgDWF8zuxAHcFpPAcPWbAYQ=	\N	f	b58ee450-c085-401a-8560-bfe0ed6272ce	armsbctls@gmail.com	t	t	f
pbkdf2_sha256$600000$29N2C0FSWTDKuduePRdNSM$OzMytxwlDC7z+rhOhAaa6zH1wsK5vHJanRuL8FlDIxk=	\N	f	54c3195f-0f07-4a4b-b2ca-1f0dd6282db4	ajaykumarma007@gmail.com	t	t	f
pbkdf2_sha256$600000$8faIMH0vlrtzVF580xuBs8$KQxINxmvs1DJCuOn1o2kfBhA3Dk9Al8MejRQ3bvmDYs=	2025-12-01 12:18:39.090064+05:30	t	e62c7306-84c1-4cb5-93c4-962454f2f3d2	ajay@gmail.com	t	t	t
\.


--
-- Data for Name: account_user_groups; Type: TABLE DATA; Schema: public; Owner: tungstonlabs
--

COPY public.account_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: account_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: tungstonlabs
--

COPY public.account_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: tungstonlabs
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: tungstonlabs
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: tungstonlabs
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add Blacklisted Token	6	add_blacklistedtoken
22	Can change Blacklisted Token	6	change_blacklistedtoken
23	Can delete Blacklisted Token	6	delete_blacklistedtoken
24	Can view Blacklisted Token	6	view_blacklistedtoken
25	Can add Outstanding Token	7	add_outstandingtoken
26	Can change Outstanding Token	7	change_outstandingtoken
27	Can delete Outstanding Token	7	delete_outstandingtoken
28	Can view Outstanding Token	7	view_outstandingtoken
29	Can add user	8	add_user
30	Can change user	8	change_user
31	Can delete user	8	delete_user
32	Can view user	8	view_user
33	Can add password reset otp	9	add_passwordresetotp
34	Can change password reset otp	9	change_passwordresetotp
35	Can delete password reset otp	9	delete_passwordresetotp
36	Can view password reset otp	9	view_passwordresetotp
37	Can add board	10	add_board
38	Can change board	10	change_board
39	Can delete board	10	delete_board
40	Can view board	10	view_board
41	Can add category	11	add_category
42	Can change category	11	change_category
43	Can delete category	11	delete_category
44	Can view category	11	view_category
45	Can add processor	12	add_processor
46	Can change processor	12	change_processor
47	Can delete processor	12	delete_processor
48	Can view processor	12	view_processor
49	Can add vendor	13	add_vendor
50	Can change vendor	13	change_vendor
51	Can delete vendor	13	delete_vendor
52	Can view vendor	13	view_vendor
53	Can add product	14	add_product
54	Can change product	14	change_product
55	Can delete product	14	delete_product
56	Can view product	14	view_product
57	Can add cart	15	add_cart
58	Can change cart	15	change_cart
59	Can delete cart	15	delete_cart
60	Can view cart	15	view_cart
61	Can add cart item	16	add_cartitem
62	Can change cart item	16	change_cartitem
63	Can delete cart item	16	delete_cartitem
64	Can view cart item	16	view_cartitem
65	Can add product inquiry	17	add_productinquiry
66	Can change product inquiry	17	change_productinquiry
67	Can delete product inquiry	17	delete_productinquiry
68	Can view product inquiry	17	view_productinquiry
69	Can add review	18	add_review
70	Can change review	18	change_review
71	Can delete review	18	delete_review
72	Can view review	18	view_review
\.


--
-- Data for Name: cart_cart; Type: TABLE DATA; Schema: public; Owner: tungstonlabs
--

COPY public.cart_cart (created_at, updated_at, id, cart_token, checked_out, user_id) FROM stdin;
2025-11-28 15:29:29.905491+05:30	2025-11-28 15:29:29.905877+05:30	5cfc5ffd-d005-433c-97c1-945442c96799	1eef1b25-d39c-46c9-93cc-6b4aecd2d448	f	\N
2025-11-28 17:12:58.478832+05:30	2025-11-28 17:12:58.478861+05:30	0d8f8650-2556-4448-aaf7-029bcab89eac	9726f5ef-679b-404c-a070-a7c3920f0706	f	\N
2025-11-28 17:20:46.069637+05:30	2025-11-28 17:20:46.069688+05:30	1396bd2e-a6fb-4879-924a-4d1a7c3c17b1	c53ecd92-f894-4118-868a-a66e859aba4d	f	\N
2025-11-28 17:20:48.023761+05:30	2025-11-28 17:20:48.023799+05:30	8d2b4dea-0837-4409-8830-ef276f39c4c0	40a20f4a-4a4e-4c97-b486-b05c2c64a1f4	f	\N
2025-11-29 10:27:44.418934+05:30	2025-11-29 10:27:44.418963+05:30	504ce07a-2c59-468a-914e-27685bf2db57	d0a6e9c8-9368-4e68-8e48-95247a1a1914	f	\N
2025-11-29 10:27:45.833386+05:30	2025-11-29 10:27:45.833442+05:30	82e7d143-0b43-4d48-bf79-5133bae6f728	b886c5d9-405c-4141-9d1a-a6a8d0ec489e	f	\N
2025-11-29 11:47:11.55504+05:30	2025-11-29 11:47:11.555076+05:30	7454bd7e-9532-4520-bbd1-070f7bbd46c4	26c07241-225e-4fba-adcf-d1c59b303802	f	\N
2025-12-02 11:13:28.899706+05:30	2025-12-02 11:13:28.899738+05:30	6498f552-9579-43f8-8662-5be1fddd6d2a	502b7532-967c-46ee-9c56-2d775f3f4824	f	\N
2025-12-02 11:15:02.877577+05:30	2025-12-02 11:15:02.877599+05:30	5e5a9336-a8cd-4056-9010-a5cd9c4fca5e	596dde67-69da-49c2-8cd0-d75f6837051e	f	\N
2025-12-02 11:15:56.120156+05:30	2025-12-02 11:15:56.120167+05:30	91448ec7-ebd8-4187-8f2e-a80c44852ad8	1e42d776-a296-4ff1-9e76-e847fc4858af	f	\N
2025-12-02 11:15:57.072416+05:30	2025-12-02 11:15:57.072428+05:30	57c9e344-2150-4b37-986d-b82a2a023140	5387ebd0-c9e5-402a-98e1-eace4913148d	f	\N
2025-12-02 11:17:49.41478+05:30	2025-12-02 11:17:49.414791+05:30	8486781c-b661-40a4-be61-6145ffb0fd0a	e4cfb736-5bf2-4f50-be29-24f1ed4608f7	f	\N
2025-12-02 11:17:50.089796+05:30	2025-12-02 11:17:50.089806+05:30	5e9297a1-6f8f-4cec-b8c7-8012aaa582ba	fe0a4cd6-992d-4116-8c68-e62f9495da3d	f	\N
2025-12-02 11:19:14.459135+05:30	2025-12-02 11:19:14.45919+05:30	b16ae723-7b1f-467b-a64e-20e382c3f727	ad343c4b-1f20-429e-b850-9a5b2dfad1e8	f	\N
2025-12-02 11:19:15.097593+05:30	2025-12-02 11:19:15.097634+05:30	f79fa0c3-11af-40ef-b5ac-8635846382a9	a83a7812-4b9e-4aa1-8d05-4da2d2ea04a2	f	\N
2025-12-02 11:29:24.56023+05:30	2025-12-02 11:29:24.560313+05:30	468f2d9e-5a69-4f52-826a-3210a053b9b0	bcff9702-9082-4ff7-865c-b07e9ecf6817	f	\N
2025-12-02 11:29:25.594284+05:30	2025-12-02 11:29:25.594377+05:30	9f60f725-7cf8-41a3-b989-d23a994b70f3	2b8aea9b-99af-4c13-abd3-fabbe815caf4	f	\N
2025-12-02 11:32:41.737939+05:30	2025-12-02 11:32:41.737951+05:30	a718e161-0403-44fa-ab15-c21330aeb32a	464533f1-dfd2-4f88-9274-5e28646ebeb0	f	\N
2025-12-02 11:32:42.492011+05:30	2025-12-02 11:32:42.492022+05:30	f18aff88-e8bd-4036-b6c7-c675062cf496	0919648b-fefd-46c5-ac17-537f63d884b3	f	\N
2025-12-02 12:10:10.253489+05:30	2025-12-02 12:10:10.253504+05:30	715f58b1-33af-489a-acd8-ac2e4ef016a6	fd9d24d6-e3f4-4f81-b3e8-580b4755ad29	f	\N
\.


--
-- Data for Name: cart_cartitem; Type: TABLE DATA; Schema: public; Owner: tungstonlabs
--

COPY public.cart_cartitem (created_at, updated_at, id, quantity, price_at_add, cart_id, product_id) FROM stdin;
2025-11-28 15:29:29.921779+05:30	2025-11-28 15:29:42.832685+05:30	511e7e89-b3a6-4aaa-8b3c-7dc406aa7716	1	0.00	5cfc5ffd-d005-433c-97c1-945442c96799	1
2025-11-28 17:12:58.489811+05:30	2025-11-28 17:12:58.489831+05:30	6417bb9e-88c4-4236-9148-2bd010354bde	1	0.00	0d8f8650-2556-4448-aaf7-029bcab89eac	2
2025-11-28 17:20:46.081928+05:30	2025-11-28 17:20:46.081967+05:30	ca9b4469-bc68-4bd4-912a-7117ee24bc59	1	0.00	1396bd2e-a6fb-4879-924a-4d1a7c3c17b1	1
2025-11-29 10:27:44.429905+05:30	2025-11-29 10:27:44.429953+05:30	54ebec09-64f0-4bb7-bb23-6541922b1f61	1	0.00	504ce07a-2c59-468a-914e-27685bf2db57	1
2025-11-29 11:47:11.563594+05:30	2025-11-29 11:47:11.563628+05:30	542be0c3-01f1-45d1-97db-16095f13c4e4	1	0.00	7454bd7e-9532-4520-bbd1-070f7bbd46c4	1
2025-12-02 11:13:28.91536+05:30	2025-12-02 11:13:28.915385+05:30	841515af-9ae1-4bcd-9ee6-57267a235801	1	0.00	6498f552-9579-43f8-8662-5be1fddd6d2a	2
2025-12-02 11:15:02.883384+05:30	2025-12-02 11:15:02.883399+05:30	0ff6dee1-f40b-494d-b2a9-5083e37474b6	1	0.00	5e5a9336-a8cd-4056-9010-a5cd9c4fca5e	1
2025-12-02 11:15:56.135539+05:30	2025-12-02 11:15:56.135551+05:30	35db5026-19a1-45ec-9f4c-54513bca52fb	1	0.00	91448ec7-ebd8-4187-8f2e-a80c44852ad8	1
2025-12-02 11:15:57.077142+05:30	2025-12-02 11:15:57.077151+05:30	a95ad9a7-ca3b-4b68-83af-06a59ccd4649	1	0.00	57c9e344-2150-4b37-986d-b82a2a023140	2
2025-12-02 11:17:49.428431+05:30	2025-12-02 11:17:49.428445+05:30	bea5b7ef-173a-4e5d-a39c-bf6ad53a673e	1	0.00	8486781c-b661-40a4-be61-6145ffb0fd0a	1
2025-12-02 11:17:50.093422+05:30	2025-12-02 11:17:50.09343+05:30	2e033bdb-128f-45ef-8d04-1696b78f8885	1	0.00	5e9297a1-6f8f-4cec-b8c7-8012aaa582ba	2
2025-12-02 11:19:14.469915+05:30	2025-12-02 11:19:14.469942+05:30	9b4e319b-7d1e-4e25-8360-2c8aaf9d0239	1	0.00	b16ae723-7b1f-467b-a64e-20e382c3f727	1
2025-12-02 11:19:15.111905+05:30	2025-12-02 11:19:15.111966+05:30	0b5d5ec3-5446-4f02-9990-0553152c34d0	1	0.00	f79fa0c3-11af-40ef-b5ac-8635846382a9	2
2025-12-02 11:29:24.574576+05:30	2025-12-02 11:29:24.57461+05:30	6ddba855-eca1-49a3-8afd-b7e94188e43a	1	0.00	468f2d9e-5a69-4f52-826a-3210a053b9b0	2
2025-12-02 11:29:25.603661+05:30	2025-12-02 11:29:25.603699+05:30	a9cdf62e-5e03-4421-b25e-1b08ad9e7e9e	1	0.00	9f60f725-7cf8-41a3-b989-d23a994b70f3	1
2025-12-02 11:32:41.743881+05:30	2025-12-02 11:32:41.743891+05:30	3028a30a-cd43-49f7-882c-9d533efafeea	1	0.00	a718e161-0403-44fa-ab15-c21330aeb32a	1
2025-12-02 11:32:42.49647+05:30	2025-12-02 11:32:42.496479+05:30	c79a7e28-02c5-47a5-9a9a-1f2d358998a6	1	0.00	f18aff88-e8bd-4036-b6c7-c675062cf496	2
2025-12-02 12:10:10.267094+05:30	2025-12-02 12:10:10.267134+05:30	e10510b3-c22b-4dbc-930a-40ace92908e4	1	0.00	715f58b1-33af-489a-acd8-ac2e4ef016a6	2
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: tungstonlabs
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2025-11-27 11:42:45.551425+05:30	1	HARDWARE	1	[{"added": {}}]	11	e62c7306-84c1-4cb5-93c4-962454f2f3d2
2	2025-11-27 11:42:55.554093+05:30	2	SOFTWARE	1	[{"added": {}}]	11	e62c7306-84c1-4cb5-93c4-962454f2f3d2
3	2025-11-27 11:43:50.276801+05:30	1	ALLWINNER (HARDWARE)	1	[{"added": {}}]	13	e62c7306-84c1-4cb5-93c4-962454f2f3d2
4	2025-11-27 11:47:28.214051+05:30	2	ROCKCHIP (HARDWARE)	1	[{"added": {}}]	13	e62c7306-84c1-4cb5-93c4-962454f2f3d2
5	2025-11-27 11:47:39.757652+05:30	3	MINI PC (HARDWARE)	1	[{"added": {}}]	13	e62c7306-84c1-4cb5-93c4-962454f2f3d2
6	2025-11-27 11:56:57.092474+05:30	1	ALLWINNER ALL3678	1	[{"added": {}}]	12	e62c7306-84c1-4cb5-93c4-962454f2f3d2
7	2025-11-27 12:03:17.516794+05:30	1	Orange Pi Zero 3	1	[{"added": {}}]	10	e62c7306-84c1-4cb5-93c4-962454f2f3d2
8	2025-11-27 12:04:49.408205+05:30	1	Integrated circuit	1	[{"added": {}}]	14	e62c7306-84c1-4cb5-93c4-962454f2f3d2
9	2025-11-27 12:27:00.976367+05:30	1	Orange Pi Zero 3	2	[{"changed": {"fields": ["Slug"]}}]	10	e62c7306-84c1-4cb5-93c4-962454f2f3d2
10	2025-11-27 12:27:32.270582+05:30	1	Orange Pi Zero 3	2	[{"changed": {"fields": ["Ethernet"]}}]	10	e62c7306-84c1-4cb5-93c4-962454f2f3d2
11	2025-11-28 09:40:28.443668+05:30	4	Thijara (SOFTWARE)	1	[{"added": {}}]	13	e62c7306-84c1-4cb5-93c4-962454f2f3d2
12	2025-11-28 09:40:36.80612+05:30	5	Rekory (SOFTWARE)	1	[{"added": {}}]	13	e62c7306-84c1-4cb5-93c4-962454f2f3d2
13	2025-11-28 10:34:18.856885+05:30	2	ALLWINNER ALL3213	1	[{"added": {}}]	12	e62c7306-84c1-4cb5-93c4-962454f2f3d2
14	2025-11-28 10:36:51.269038+05:30	2	Media Processors	1	[{"added": {}}]	14	e62c7306-84c1-4cb5-93c4-962454f2f3d2
15	2025-11-28 10:37:13.673375+05:30	2	Media Processors	2	[{"changed": {"fields": ["Processor"]}}]	14	e62c7306-84c1-4cb5-93c4-962454f2f3d2
16	2025-11-28 15:41:23.163186+05:30	1	ALLWINNER (HARDWARE)	2	[{"changed": {"fields": ["Image"]}}]	13	e62c7306-84c1-4cb5-93c4-962454f2f3d2
17	2025-11-28 15:43:49.02887+05:30	2	ROCKCHIP (HARDWARE)	2	[{"changed": {"fields": ["Image"]}}]	13	e62c7306-84c1-4cb5-93c4-962454f2f3d2
18	2025-11-28 15:52:49.153363+05:30	3	MINI PC (HARDWARE)	2	[{"changed": {"fields": ["Image"]}}]	13	e62c7306-84c1-4cb5-93c4-962454f2f3d2
19	2025-11-28 15:56:31.265596+05:30	4	Thijara (SOFTWARE)	2	[{"changed": {"fields": ["Image"]}}]	13	e62c7306-84c1-4cb5-93c4-962454f2f3d2
20	2025-11-28 15:57:37.191273+05:30	5	Rekory (SOFTWARE)	2	[{"changed": {"fields": ["Image"]}}]	13	e62c7306-84c1-4cb5-93c4-962454f2f3d2
21	2025-11-28 16:17:48.243672+05:30	6	ABC (SOFTWARE)	1	[{"added": {}}]	13	e62c7306-84c1-4cb5-93c4-962454f2f3d2
22	2025-11-28 17:42:15.867527+05:30	3	ROCKCHIP RK3588	1	[{"added": {}}]	12	e62c7306-84c1-4cb5-93c4-962454f2f3d2
23	2025-11-29 11:05:16.346878+05:30	5	Rekory (SOFTWARE)	3		13	e62c7306-84c1-4cb5-93c4-962454f2f3d2
24	2025-11-29 11:05:27.763466+05:30	4	Thijara (SOFTWARE)	3		13	e62c7306-84c1-4cb5-93c4-962454f2f3d2
25	2025-11-29 11:05:34.666246+05:30	6	ABC (SOFTWARE)	3		13	e62c7306-84c1-4cb5-93c4-962454f2f3d2
26	2025-11-29 11:06:57.932649+05:30	7	Thijara (SOFTWARE)	1	[{"added": {}}]	13	e62c7306-84c1-4cb5-93c4-962454f2f3d2
27	2025-11-29 11:21:24.876543+05:30	7	Thijara (SOFTWARE)	2	[{"changed": {"fields": ["Image"]}}]	13	e62c7306-84c1-4cb5-93c4-962454f2f3d2
28	2025-11-29 11:23:48.939167+05:30	8	Rekory (SOFTWARE)	1	[{"added": {}}]	13	e62c7306-84c1-4cb5-93c4-962454f2f3d2
29	2025-12-02 12:15:16.203785+05:30	9	Market-ERP (SOFTWARE)	1	[{"added": {}}]	13	e62c7306-84c1-4cb5-93c4-962454f2f3d2
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: tungstonlabs
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	token_blacklist	blacklistedtoken
7	token_blacklist	outstandingtoken
8	account	user
9	account	passwordresetotp
10	product	board
11	product	category
12	product	processor
13	product	vendor
14	product	product
15	cart	cart
16	cart	cartitem
17	inquiries	productinquiry
18	review	review
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: tungstonlabs
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-11-27 11:12:24.11643+05:30
2	contenttypes	0002_remove_content_type_name	2025-11-27 11:12:24.122053+05:30
3	auth	0001_initial	2025-11-27 11:12:24.162525+05:30
4	auth	0002_alter_permission_name_max_length	2025-11-27 11:12:24.166915+05:30
5	auth	0003_alter_user_email_max_length	2025-11-27 11:12:24.170855+05:30
6	auth	0004_alter_user_username_opts	2025-11-27 11:12:24.174773+05:30
7	auth	0005_alter_user_last_login_null	2025-11-27 11:12:24.178279+05:30
8	auth	0006_require_contenttypes_0002	2025-11-27 11:12:24.17965+05:30
9	auth	0007_alter_validators_add_error_messages	2025-11-27 11:12:24.182837+05:30
10	auth	0008_alter_user_username_max_length	2025-11-27 11:12:24.187338+05:30
11	auth	0009_alter_user_last_name_max_length	2025-11-27 11:12:24.19083+05:30
12	auth	0010_alter_group_name_max_length	2025-11-27 11:12:24.195487+05:30
13	auth	0011_update_proxy_permissions	2025-11-27 11:12:24.199335+05:30
14	auth	0012_alter_user_first_name_max_length	2025-11-27 11:12:24.203755+05:30
15	account	0001_initial	2025-11-27 11:12:24.238693+05:30
16	account	0002_passwordresetotp	2025-11-27 11:12:24.248374+05:30
17	admin	0001_initial	2025-11-27 11:12:24.261769+05:30
18	admin	0002_logentry_remove_auto_add	2025-11-27 11:12:24.266817+05:30
19	admin	0003_logentry_add_action_flag_choices	2025-11-27 11:12:24.271747+05:30
21	cart	0001_initial	2025-11-27 11:12:24.355118+05:30
22	inquiries	0001_initial	2025-11-27 11:12:24.376717+05:30
23	review	0001_initial	2025-11-27 11:12:24.392676+05:30
24	sessions	0001_initial	2025-11-27 11:12:24.399563+05:30
25	token_blacklist	0001_initial	2025-11-27 11:12:24.434604+05:30
26	token_blacklist	0002_outstandingtoken_jti_hex	2025-11-27 11:12:24.44052+05:30
27	token_blacklist	0003_auto_20171017_2007	2025-11-27 11:12:24.452751+05:30
28	token_blacklist	0004_auto_20171017_2013	2025-11-27 11:12:24.460895+05:30
29	token_blacklist	0005_remove_outstandingtoken_jti	2025-11-27 11:12:24.467634+05:30
30	token_blacklist	0006_auto_20171017_2113	2025-11-27 11:12:24.474075+05:30
31	token_blacklist	0007_auto_20171017_2214	2025-11-27 11:12:24.502563+05:30
32	token_blacklist	0008_migrate_to_bigautofield	2025-11-27 11:12:24.538911+05:30
33	token_blacklist	0010_fix_migrate_to_bigautofield	2025-11-27 11:12:24.556486+05:30
34	token_blacklist	0011_linearizes_history	2025-11-27 11:12:24.558574+05:30
35	token_blacklist	0012_alter_outstandingtoken_user	2025-11-27 11:12:24.568752+05:30
36	token_blacklist	0013_alter_blacklistedtoken_options_and_more	2025-11-27 11:12:24.576311+05:30
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: tungstonlabs
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
n4hhfwhugjaey0f6xirtuzf59ulso0kc	.eJxVjTkOwjAQRe_imlheZsY2JT1niMZjh7AokbJUiLuTSCmg_u-9_1Ytr0vfrnOd2ntRZ1XJSfCGmghiG5CMTfICTSIHCJ3rfHHq9Ktllmcddrc8eLiNWsZhme5Z74g-1llfx1Jfl4P9C_Q895vNLjIkxJwisjFcQ_TWBfLbPedkyAIUsVSqEJOtGAqjBYeBspdk1OcLd5E_vw:1vOVEv:5UF24pTxo_yWDSI7PhimNy_zMy8g7Hx4n0mFTzgJcD0	2025-12-11 11:42:25.360288+05:30
9sht1bjz3qgmahlhjobnhtck91byuzns	.eJxVjTkOwjAQRe_imlheZsY2JT1niMZjh7AokbJUiLuTSCmg_u-9_1Ytr0vfrnOd2ntRZ1XJSfCGmghiG5CMTfICTSIHCJ3rfHHq9Ktllmcddrc8eLiNWsZhme5Z74g-1llfx1Jfl4P9C_Q895vNLjIkxJwisjFcQ_TWBfLbPedkyAIUsVSqEJOtGAqjBYeBspdk1OcLd5E_vw:1vPxiB:9dr0JcHeqKgPFNALfNO0ikPRMIux5d75frWbNw_QlAE	2025-12-15 12:18:39.092697+05:30
\.


--
-- Data for Name: inquiries_productinquiry; Type: TABLE DATA; Schema: public; Owner: tungstonlabs
--

COPY public.inquiries_productinquiry (created_at, updated_at, id, first_name, last_name, company_name, email, phone, address, country, state, delivery_location, description, status, cart_id) FROM stdin;
\.


--
-- Data for Name: inquiries_productinquiry_products; Type: TABLE DATA; Schema: public; Owner: tungstonlabs
--

COPY public.inquiries_productinquiry_products (id, productinquiry_id, product_id) FROM stdin;
\.


--
-- Data for Name: product_board; Type: TABLE DATA; Schema: public; Owner: tungstonlabs
--

COPY public.product_board (id, created_at, updated_at, slug, name, short_tagline, dram_config, emmc_config, storage_slots, wifi, ethernet, video_connectors, expansion, gpio_headers, power_input, form_factor, additional_info, is_active, image, processor_id) FROM stdin;
1	2025-11-27 12:03:17.509939+05:30	2025-11-27 12:27:32.269485+05:30	pizero	Orange Pi Zero 3	Simply Irresistible.	20	x8	SDR104	Dual-band 802.11ac wireless LAN.	Gigabit	2 × micro-HDMI® ports (up to 4Kp60 supported)	Standard 40-pin GPIO header	Standard 40-pin GPIO header	5V DC via USB-C connector	Single Board Computer	\N	t		1
\.


--
-- Data for Name: product_category; Type: TABLE DATA; Schema: public; Owner: tungstonlabs
--

COPY public.product_category (id, created_at, updated_at, name) FROM stdin;
1	2025-11-27 11:42:45.546597+05:30	2025-11-27 11:42:45.546609+05:30	HARDWARE
2	2025-11-27 11:42:55.553077+05:30	2025-11-27 11:42:55.553112+05:30	SOFTWARE
\.


--
-- Data for Name: product_processor; Type: TABLE DATA; Schema: public; Owner: tungstonlabs
--

COPY public.product_processor (id, created_at, updated_at, code, name, cpu_cores, cpu_arch, arch_bits, l1_cache_kb, l2_cache_kb, gpu, npu_tops, max_dram_gb, hdmi, lvds, edp, dp, mipi_dsi, usb2_ports, usb3_ports, pcie_desc, ethernet_cap, sata, sdio, extra, image, vendor_id) FROM stdin;
1	2025-11-27 11:56:57.082748+05:30	2025-11-27 11:56:57.082767+05:30	ALL3678	ALLPROZ3678	3	28	189	2020	120	74	1.47	20	t	f	t	f	f	2	3	x4	RJ45	f	t	\N		1
2	2025-11-28 10:34:18.848934+05:30	2025-11-28 10:34:18.848951+05:30	ALL3213	ALLWINNERPRO172	2	12	12	312	256	Dedicated	\N	32	t	f	f	f	f	\N	\N	Gen4	1Gbps	f	t	\N	processors/Allwinner-H618-TV-Box-Android-12.jpg	1
3	2025-11-28 17:42:15.860396+05:30	2025-11-28 17:42:15.860412+05:30	RK3588	Octa-core System-on-Chip (SoC)	8	ARM v8.2-A	64	76	512	ARM Mali-G610 MP4	6.00	32	t	t	t	t	t	22.0	5	1x PCIe 3.0 (4-lane or 2x 2-lane), 3x Combo PIPE PHYs (PCIe 2.1 or SATA 3.0)	Dual Gigabit Ethernet (2x GMAC)	t	t	{"Audio Interfaces": "Multi-channel I2S/PDM/TDM for professional audio applications.", "Security Features": "Supports hardware virtualization, TrustZone, and various crypto engines.", "Video Processing Unit (VPU)": "Supports 8Kp60 H.265/VP9/AVS2 decode and 8Kp30 H.265/H.264 encode.", "Image Signal Processor (ISP)": "48MP multi-channel ISP for advanced camera processing."}	processors/Rock_Pi_4B_cropped_RK3399_je3gaZO.jpg	2
\.


--
-- Data for Name: product_product; Type: TABLE DATA; Schema: public; Owner: tungstonlabs
--

COPY public.product_product (id, created_at, updated_at, name, ram_gb, ram_expandable_upto, storage, price, image, available, board_id, processor_id) FROM stdin;
1	2025-11-27 12:04:49.39925+05:30	2025-11-27 12:04:49.399272+05:30	Integrated circuit	20	32	256	2000.00	products/41Jauw0GkPL._AC_UF10001000_QL80_.jpg	t	1	1
2	2025-11-28 10:36:51.25855+05:30	2025-11-28 10:37:13.670978+05:30	Media Processors	12	64	128	3000.00	products/Allwinner-H618-TV-Box-Android-12.jpg	t	1	1
\.


--
-- Data for Name: product_vendor; Type: TABLE DATA; Schema: public; Owner: tungstonlabs
--

COPY public.product_vendor (id, created_at, updated_at, name, category_id, image, description, website_url) FROM stdin;
1	2025-11-27 11:43:50.273311+05:30	2025-11-28 15:41:23.156495+05:30	ALLWINNER	1	vendors/Allwinner.svg.png	\N	\N
2	2025-11-27 11:47:28.211706+05:30	2025-11-28 15:43:49.026287+05:30	ROCKCHIP	1	vendors/logo03_s.png	\N	\N
3	2025-11-27 11:47:39.75671+05:30	2025-11-28 15:52:49.147517+05:30	MINI PC	1	vendors/mini-pc-icon-small-computer-symbol-vector-18650204.avif	\N	\N
7	2025-11-29 11:06:57.930414+05:30	2025-11-29 11:21:24.871736+05:30	Thijara	2	vendors/logotijara_2.png	Real-Time Market Visibility Access accurate, up-to-date stock availability across the entire wholesale network. This helps eliminate uncertainty and keeps you fully aligned with real-time market conditions. Centralized Trading Platform Manage stock listings, orders, and interactions seamlessly in one unified system. This ensures smoother coordination and reduces the need for multiple tools or manual follow-ups.	http://178.248.112.16:84/
8	2025-11-29 11:23:48.93577+05:30	2025-11-29 11:23:48.935795+05:30	Rekory	2	vendors/splash.png	Rekory is a simple, user-friendly HR app available on both iOS and Android, making workforce management easy from anywhere. It offers everything from employee onboarding and performance tracking to advanced HR analytics—all in one place. Designed for modern teams, Rekory helps streamline HR tasks and boost productivity.	http://178.248.112.16:86/
9	2025-12-02 12:15:16.196977+05:30	2025-12-02 12:15:16.196988+05:30	Market-ERP	2	vendors/msplogo.png	MSP is a comprehensive Enterprise Resource Planning (ERP) solution designed specifically for the unique demands of the modern fish market industry.\r\nThis robust platform streamlines the entire supply chain, from initial catch or aquaculture sourcing to final sales and distribution. Key features include real-time inventory management, advanced catch tracking and traceability, production planning for processing, and integrated financial management.	https://msp.tungstonlabs.com/login
\.


--
-- Data for Name: review_review; Type: TABLE DATA; Schema: public; Owner: tungstonlabs
--

COPY public.review_review (created_at, updated_at, id, name, email, rating, review, approved, product_id) FROM stdin;
\.


--
-- Data for Name: token_blacklist_blacklistedtoken; Type: TABLE DATA; Schema: public; Owner: tungstonlabs
--

COPY public.token_blacklist_blacklistedtoken (id, blacklisted_at, token_id) FROM stdin;
1	2025-11-28 10:08:56.132064+05:30	1
\.


--
-- Data for Name: token_blacklist_outstandingtoken; Type: TABLE DATA; Schema: public; Owner: tungstonlabs
--

COPY public.token_blacklist_outstandingtoken (id, token, created_at, expires_at, user_id, jti) FROM stdin;
1	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2NDgzMTU4NiwiaWF0IjoxNzY0MjI2Nzg2LCJqdGkiOiI3NGZlYjgwNDhhMDE0YTUzYjk3OTY1N2MyZGViZjM2MyIsInVzZXJfaWQiOiJiNThlZTQ1MC1jMDg1LTQwMWEtODU2MC1iZmUwZWQ2MjcyY2UifQ.4v_FP985g9uq1rlMqCkToECSfexbQUskr1e0e7pUKBI	2025-11-27 12:29:46.213715+05:30	2025-12-04 12:29:46+05:30	b58ee450-c085-401a-8560-bfe0ed6272ce	74feb8048a014a53b979657c2debf363
2	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2NDkwOTU4NCwiaWF0IjoxNzY0MzA0Nzg0LCJqdGkiOiI1OTAzY2M3YTY1YTM0Mjk5ODQxYzk3NTE4YzYyMjkyYyIsInVzZXJfaWQiOiI1NGMzMTk1Zi0wZjA3LTRhNGItYjJjYS0xZjBkZDYyODJkYjQifQ.9-uHTmIvommIcPUTNig9O3N7Cu4JJsf4vMelUljjkYo	2025-11-28 10:09:44.838922+05:30	2025-12-05 10:09:44+05:30	54c3195f-0f07-4a4b-b2ca-1f0dd6282db4	5903cc7a65a34299841c97518c62292c
\.


--
-- Name: account_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: tungstonlabs
--

SELECT pg_catalog.setval('public.account_user_groups_id_seq', 1, false);


--
-- Name: account_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: tungstonlabs
--

SELECT pg_catalog.setval('public.account_user_user_permissions_id_seq', 1, false);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: tungstonlabs
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: tungstonlabs
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: tungstonlabs
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 72, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: tungstonlabs
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 29, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: tungstonlabs
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 18, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: tungstonlabs
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 40, true);


--
-- Name: inquiries_productinquiry_products_id_seq; Type: SEQUENCE SET; Schema: public; Owner: tungstonlabs
--

SELECT pg_catalog.setval('public.inquiries_productinquiry_products_id_seq', 1, false);


--
-- Name: product_board_id_seq; Type: SEQUENCE SET; Schema: public; Owner: tungstonlabs
--

SELECT pg_catalog.setval('public.product_board_id_seq', 1, true);


--
-- Name: product_category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: tungstonlabs
--

SELECT pg_catalog.setval('public.product_category_id_seq', 2, true);


--
-- Name: product_processor_id_seq; Type: SEQUENCE SET; Schema: public; Owner: tungstonlabs
--

SELECT pg_catalog.setval('public.product_processor_id_seq', 3, true);


--
-- Name: product_product_id_seq; Type: SEQUENCE SET; Schema: public; Owner: tungstonlabs
--

SELECT pg_catalog.setval('public.product_product_id_seq', 2, true);


--
-- Name: product_vendor_id_seq; Type: SEQUENCE SET; Schema: public; Owner: tungstonlabs
--

SELECT pg_catalog.setval('public.product_vendor_id_seq', 9, true);


--
-- Name: token_blacklist_blacklistedtoken_id_seq; Type: SEQUENCE SET; Schema: public; Owner: tungstonlabs
--

SELECT pg_catalog.setval('public.token_blacklist_blacklistedtoken_id_seq', 4, true);


--
-- Name: token_blacklist_outstandingtoken_id_seq; Type: SEQUENCE SET; Schema: public; Owner: tungstonlabs
--

SELECT pg_catalog.setval('public.token_blacklist_outstandingtoken_id_seq', 2, true);


--
-- Name: account_passwordresetotp account_passwordresetotp_pkey; Type: CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.account_passwordresetotp
    ADD CONSTRAINT account_passwordresetotp_pkey PRIMARY KEY (id);


--
-- Name: account_user account_user_email_key; Type: CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.account_user
    ADD CONSTRAINT account_user_email_key UNIQUE (email);


--
-- Name: account_user_groups account_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.account_user_groups
    ADD CONSTRAINT account_user_groups_pkey PRIMARY KEY (id);


--
-- Name: account_user_groups account_user_groups_user_id_group_id_4d09af3e_uniq; Type: CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.account_user_groups
    ADD CONSTRAINT account_user_groups_user_id_group_id_4d09af3e_uniq UNIQUE (user_id, group_id);


--
-- Name: account_user account_user_pkey; Type: CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.account_user
    ADD CONSTRAINT account_user_pkey PRIMARY KEY (id);


--
-- Name: account_user_user_permissions account_user_user_permis_user_id_permission_id_48bdd28b_uniq; Type: CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.account_user_user_permissions
    ADD CONSTRAINT account_user_user_permis_user_id_permission_id_48bdd28b_uniq UNIQUE (user_id, permission_id);


--
-- Name: account_user_user_permissions account_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.account_user_user_permissions
    ADD CONSTRAINT account_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: cart_cart cart_cart_pkey; Type: CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.cart_cart
    ADD CONSTRAINT cart_cart_pkey PRIMARY KEY (id);


--
-- Name: cart_cartitem cart_cartitem_cart_id_product_id_53cce7c3_uniq; Type: CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.cart_cartitem
    ADD CONSTRAINT cart_cartitem_cart_id_product_id_53cce7c3_uniq UNIQUE (cart_id, product_id);


--
-- Name: cart_cartitem cart_cartitem_pkey; Type: CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.cart_cartitem
    ADD CONSTRAINT cart_cartitem_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: inquiries_productinquiry inquiries_productinquiry_pkey; Type: CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.inquiries_productinquiry
    ADD CONSTRAINT inquiries_productinquiry_pkey PRIMARY KEY (id);


--
-- Name: inquiries_productinquiry_products inquiries_productinquiry_productinquiry_id_produc_fb993131_uniq; Type: CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.inquiries_productinquiry_products
    ADD CONSTRAINT inquiries_productinquiry_productinquiry_id_produc_fb993131_uniq UNIQUE (productinquiry_id, product_id);


--
-- Name: inquiries_productinquiry_products inquiries_productinquiry_products_pkey; Type: CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.inquiries_productinquiry_products
    ADD CONSTRAINT inquiries_productinquiry_products_pkey PRIMARY KEY (id);


--
-- Name: product_board product_board_pkey; Type: CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.product_board
    ADD CONSTRAINT product_board_pkey PRIMARY KEY (id);


--
-- Name: product_board product_board_slug_key; Type: CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.product_board
    ADD CONSTRAINT product_board_slug_key UNIQUE (slug);


--
-- Name: product_category product_category_name_key; Type: CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.product_category
    ADD CONSTRAINT product_category_name_key UNIQUE (name);


--
-- Name: product_category product_category_pkey; Type: CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.product_category
    ADD CONSTRAINT product_category_pkey PRIMARY KEY (id);


--
-- Name: product_processor product_processor_code_key; Type: CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.product_processor
    ADD CONSTRAINT product_processor_code_key UNIQUE (code);


--
-- Name: product_processor product_processor_pkey; Type: CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.product_processor
    ADD CONSTRAINT product_processor_pkey PRIMARY KEY (id);


--
-- Name: product_product product_product_pkey; Type: CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.product_product
    ADD CONSTRAINT product_product_pkey PRIMARY KEY (id);


--
-- Name: product_vendor product_vendor_name_key; Type: CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.product_vendor
    ADD CONSTRAINT product_vendor_name_key UNIQUE (name);


--
-- Name: product_vendor product_vendor_pkey; Type: CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.product_vendor
    ADD CONSTRAINT product_vendor_pkey PRIMARY KEY (id);


--
-- Name: review_review review_review_pkey; Type: CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.review_review
    ADD CONSTRAINT review_review_pkey PRIMARY KEY (id);


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_pkey PRIMARY KEY (id);


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_key; Type: CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_key UNIQUE (token_id);


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq; Type: CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq UNIQUE (jti);


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_pkey PRIMARY KEY (id);


--
-- Name: account_passwordresetotp_user_id_b002be52; Type: INDEX; Schema: public; Owner: tungstonlabs
--

CREATE INDEX account_passwordresetotp_user_id_b002be52 ON public.account_passwordresetotp USING btree (user_id);


--
-- Name: account_user_email_0bd7c421_like; Type: INDEX; Schema: public; Owner: tungstonlabs
--

CREATE INDEX account_user_email_0bd7c421_like ON public.account_user USING btree (email varchar_pattern_ops);


--
-- Name: account_user_groups_group_id_6c71f749; Type: INDEX; Schema: public; Owner: tungstonlabs
--

CREATE INDEX account_user_groups_group_id_6c71f749 ON public.account_user_groups USING btree (group_id);


--
-- Name: account_user_groups_user_id_14345e7b; Type: INDEX; Schema: public; Owner: tungstonlabs
--

CREATE INDEX account_user_groups_user_id_14345e7b ON public.account_user_groups USING btree (user_id);


--
-- Name: account_user_user_permissions_permission_id_66c44191; Type: INDEX; Schema: public; Owner: tungstonlabs
--

CREATE INDEX account_user_user_permissions_permission_id_66c44191 ON public.account_user_user_permissions USING btree (permission_id);


--
-- Name: account_user_user_permissions_user_id_cc42d270; Type: INDEX; Schema: public; Owner: tungstonlabs
--

CREATE INDEX account_user_user_permissions_user_id_cc42d270 ON public.account_user_user_permissions USING btree (user_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: tungstonlabs
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: tungstonlabs
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: tungstonlabs
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: tungstonlabs
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: cart_cart_cart_token_a10c8d28; Type: INDEX; Schema: public; Owner: tungstonlabs
--

CREATE INDEX cart_cart_cart_token_a10c8d28 ON public.cart_cart USING btree (cart_token);


--
-- Name: cart_cart_cart_token_a10c8d28_like; Type: INDEX; Schema: public; Owner: tungstonlabs
--

CREATE INDEX cart_cart_cart_token_a10c8d28_like ON public.cart_cart USING btree (cart_token varchar_pattern_ops);


--
-- Name: cart_cart_user_id_9b4220b9; Type: INDEX; Schema: public; Owner: tungstonlabs
--

CREATE INDEX cart_cart_user_id_9b4220b9 ON public.cart_cart USING btree (user_id);


--
-- Name: cart_cartitem_cart_id_370ad265; Type: INDEX; Schema: public; Owner: tungstonlabs
--

CREATE INDEX cart_cartitem_cart_id_370ad265 ON public.cart_cartitem USING btree (cart_id);


--
-- Name: cart_cartitem_product_id_b24e265a; Type: INDEX; Schema: public; Owner: tungstonlabs
--

CREATE INDEX cart_cartitem_product_id_b24e265a ON public.cart_cartitem USING btree (product_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: tungstonlabs
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: tungstonlabs
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: tungstonlabs
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: tungstonlabs
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: inquiries_productinquiry_cart_id_0d652583; Type: INDEX; Schema: public; Owner: tungstonlabs
--

CREATE INDEX inquiries_productinquiry_cart_id_0d652583 ON public.inquiries_productinquiry USING btree (cart_id);


--
-- Name: inquiries_productinquiry_products_product_id_a90b66c1; Type: INDEX; Schema: public; Owner: tungstonlabs
--

CREATE INDEX inquiries_productinquiry_products_product_id_a90b66c1 ON public.inquiries_productinquiry_products USING btree (product_id);


--
-- Name: inquiries_productinquiry_products_productinquiry_id_91141357; Type: INDEX; Schema: public; Owner: tungstonlabs
--

CREATE INDEX inquiries_productinquiry_products_productinquiry_id_91141357 ON public.inquiries_productinquiry_products USING btree (productinquiry_id);


--
-- Name: product_board_processor_id_db89cca1; Type: INDEX; Schema: public; Owner: tungstonlabs
--

CREATE INDEX product_board_processor_id_db89cca1 ON public.product_board USING btree (processor_id);


--
-- Name: product_board_slug_9251b8ec_like; Type: INDEX; Schema: public; Owner: tungstonlabs
--

CREATE INDEX product_board_slug_9251b8ec_like ON public.product_board USING btree (slug varchar_pattern_ops);


--
-- Name: product_category_name_905278b8_like; Type: INDEX; Schema: public; Owner: tungstonlabs
--

CREATE INDEX product_category_name_905278b8_like ON public.product_category USING btree (name varchar_pattern_ops);


--
-- Name: product_processor_code_7ce2708f_like; Type: INDEX; Schema: public; Owner: tungstonlabs
--

CREATE INDEX product_processor_code_7ce2708f_like ON public.product_processor USING btree (code varchar_pattern_ops);


--
-- Name: product_processor_vendor_id_f8ef9999; Type: INDEX; Schema: public; Owner: tungstonlabs
--

CREATE INDEX product_processor_vendor_id_f8ef9999 ON public.product_processor USING btree (vendor_id);


--
-- Name: product_product_board_id_026f13ef; Type: INDEX; Schema: public; Owner: tungstonlabs
--

CREATE INDEX product_product_board_id_026f13ef ON public.product_product USING btree (board_id);


--
-- Name: product_product_processor_id_97adcfbd; Type: INDEX; Schema: public; Owner: tungstonlabs
--

CREATE INDEX product_product_processor_id_97adcfbd ON public.product_product USING btree (processor_id);


--
-- Name: product_vendor_category_id_0ae0962c; Type: INDEX; Schema: public; Owner: tungstonlabs
--

CREATE INDEX product_vendor_category_id_0ae0962c ON public.product_vendor USING btree (category_id);


--
-- Name: product_vendor_name_fc1ae959_like; Type: INDEX; Schema: public; Owner: tungstonlabs
--

CREATE INDEX product_vendor_name_fc1ae959_like ON public.product_vendor USING btree (name varchar_pattern_ops);


--
-- Name: review_review_product_id_bee66c28; Type: INDEX; Schema: public; Owner: tungstonlabs
--

CREATE INDEX review_review_product_id_bee66c28 ON public.review_review USING btree (product_id);


--
-- Name: token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like; Type: INDEX; Schema: public; Owner: tungstonlabs
--

CREATE INDEX token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like ON public.token_blacklist_outstandingtoken USING btree (jti varchar_pattern_ops);


--
-- Name: token_blacklist_outstandingtoken_user_id_83bc629a; Type: INDEX; Schema: public; Owner: tungstonlabs
--

CREATE INDEX token_blacklist_outstandingtoken_user_id_83bc629a ON public.token_blacklist_outstandingtoken USING btree (user_id);


--
-- Name: account_passwordresetotp account_passwordresetotp_user_id_b002be52_fk_account_user_id; Type: FK CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.account_passwordresetotp
    ADD CONSTRAINT account_passwordresetotp_user_id_b002be52_fk_account_user_id FOREIGN KEY (user_id) REFERENCES public.account_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: account_user_groups account_user_groups_group_id_6c71f749_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.account_user_groups
    ADD CONSTRAINT account_user_groups_group_id_6c71f749_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: account_user_groups account_user_groups_user_id_14345e7b_fk_account_user_id; Type: FK CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.account_user_groups
    ADD CONSTRAINT account_user_groups_user_id_14345e7b_fk_account_user_id FOREIGN KEY (user_id) REFERENCES public.account_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: account_user_user_permissions account_user_user_pe_permission_id_66c44191_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.account_user_user_permissions
    ADD CONSTRAINT account_user_user_pe_permission_id_66c44191_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: account_user_user_permissions account_user_user_pe_user_id_cc42d270_fk_account_u; Type: FK CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.account_user_user_permissions
    ADD CONSTRAINT account_user_user_pe_user_id_cc42d270_fk_account_u FOREIGN KEY (user_id) REFERENCES public.account_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cart_cart cart_cart_user_id_9b4220b9_fk_account_user_id; Type: FK CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.cart_cart
    ADD CONSTRAINT cart_cart_user_id_9b4220b9_fk_account_user_id FOREIGN KEY (user_id) REFERENCES public.account_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cart_cartitem cart_cartitem_cart_id_370ad265_fk_cart_cart_id; Type: FK CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.cart_cartitem
    ADD CONSTRAINT cart_cartitem_cart_id_370ad265_fk_cart_cart_id FOREIGN KEY (cart_id) REFERENCES public.cart_cart(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cart_cartitem cart_cartitem_product_id_b24e265a_fk_product_product_id; Type: FK CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.cart_cartitem
    ADD CONSTRAINT cart_cartitem_product_id_b24e265a_fk_product_product_id FOREIGN KEY (product_id) REFERENCES public.product_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_account_user_id; Type: FK CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_account_user_id FOREIGN KEY (user_id) REFERENCES public.account_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inquiries_productinquiry_products inquiries_productinq_product_id_a90b66c1_fk_product_p; Type: FK CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.inquiries_productinquiry_products
    ADD CONSTRAINT inquiries_productinq_product_id_a90b66c1_fk_product_p FOREIGN KEY (product_id) REFERENCES public.product_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inquiries_productinquiry_products inquiries_productinq_productinquiry_id_91141357_fk_inquiries; Type: FK CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.inquiries_productinquiry_products
    ADD CONSTRAINT inquiries_productinq_productinquiry_id_91141357_fk_inquiries FOREIGN KEY (productinquiry_id) REFERENCES public.inquiries_productinquiry(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inquiries_productinquiry inquiries_productinquiry_cart_id_0d652583_fk_cart_cart_id; Type: FK CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.inquiries_productinquiry
    ADD CONSTRAINT inquiries_productinquiry_cart_id_0d652583_fk_cart_cart_id FOREIGN KEY (cart_id) REFERENCES public.cart_cart(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: product_board product_board_processor_id_db89cca1_fk_product_processor_id; Type: FK CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.product_board
    ADD CONSTRAINT product_board_processor_id_db89cca1_fk_product_processor_id FOREIGN KEY (processor_id) REFERENCES public.product_processor(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: product_processor product_processor_vendor_id_f8ef9999_fk_product_vendor_id; Type: FK CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.product_processor
    ADD CONSTRAINT product_processor_vendor_id_f8ef9999_fk_product_vendor_id FOREIGN KEY (vendor_id) REFERENCES public.product_vendor(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: product_product product_product_board_id_026f13ef_fk_product_board_id; Type: FK CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.product_product
    ADD CONSTRAINT product_product_board_id_026f13ef_fk_product_board_id FOREIGN KEY (board_id) REFERENCES public.product_board(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: product_product product_product_processor_id_97adcfbd_fk_product_processor_id; Type: FK CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.product_product
    ADD CONSTRAINT product_product_processor_id_97adcfbd_fk_product_processor_id FOREIGN KEY (processor_id) REFERENCES public.product_processor(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: product_vendor product_vendor_category_id_0ae0962c_fk_product_category_id; Type: FK CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.product_vendor
    ADD CONSTRAINT product_vendor_category_id_0ae0962c_fk_product_category_id FOREIGN KEY (category_id) REFERENCES public.product_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: review_review review_review_product_id_bee66c28_fk_product_product_id; Type: FK CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.review_review
    ADD CONSTRAINT review_review_product_id_bee66c28_fk_product_product_id FOREIGN KEY (product_id) REFERENCES public.product_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk; Type: FK CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk FOREIGN KEY (token_id) REFERENCES public.token_blacklist_outstandingtoken(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outs_user_id_83bc629a_fk_account_u; Type: FK CONSTRAINT; Schema: public; Owner: tungstonlabs
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outs_user_id_83bc629a_fk_account_u FOREIGN KEY (user_id) REFERENCES public.account_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict lvzkCK1OSwqgmhcLxnLiz1J7dqXBbJ8gg5sq6JMj7lofOaCQgDAIyQVFg9JB4wc

