# Generated by Django 4.2.24 on 2025-09-24 04:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=400)),
                ('description', models.JSONField(blank=True, default=list, null=True)),
                ('specs', models.JSONField(blank=True, default=dict, null=True)),
                ('additional_info', models.JSONField(blank=True, default=dict, null=True)),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
