# Generated by Django 4.2.24 on 2025-12-04 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processor',
            name='arch_bits',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='cpu_arch',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='cpu_cores',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='ethernet_cap',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='l1_cache_kb',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='l2_cache_kb',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='max_dram_gb',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='mipi_dsi',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='npu_tops',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='pcie_desc',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='ram_expandable_upto',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='usb2_ports',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='usb3_ports',
        ),
        migrations.AddField(
            model_name='processor',
            name='architecture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='processor',
            name='cpu',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='processor',
            name='dsi',
            field=models.CharField(choices=[('none', 'Not Supported'), ('2-lane', 'MIPI DSI 2-lane'), ('4-lane', 'MIPI DSI 4-lane')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='processor',
            name='ethernet_mac',
            field=models.CharField(choices=[('none', 'Not Supported'), ('10/100', '10/100 Mbps MAC'), ('1g', '1G Ethernet MAC'), ('2.5g', '2.5G Ethernet MAC')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='processor',
            name='l1_cache',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='processor',
            name='l2_l3_cache',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='processor',
            name='max_clock',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='processor',
            name='max_ram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='processor',
            name='npu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='processor',
            name='soc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='processor',
            name='usb2',
            field=models.CharField(choices=[('none', 'Not Supported'), ('1-port', '1 Port'), ('2-port', '2 Ports'), ('4-port', '4 Ports')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='processor',
            name='usb3',
            field=models.CharField(choices=[('none', 'Not Supported'), ('1-port', '1 Port'), ('2-port', '2 Ports')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='audio_amplifier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='debug_port',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='dp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='dsi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='edp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='ethernet_10_100',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='ethernet_1g',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='hdmi_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='hdmi_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='lvds',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='memory_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='rs232',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='rs485',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='speaker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='type_c',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='usb2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='usb3',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='processor',
            name='dp',
            field=models.CharField(choices=[('none', 'Not Supported'), ('1.2', 'DisplayPort 1.2'), ('1.4', 'DisplayPort 1.4'), ('2.0', 'DisplayPort 2.0')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='processor',
            name='edp',
            field=models.CharField(choices=[('none', 'Not Supported'), ('1.1', 'eDP 1.1'), ('1.2', 'eDP 1.2'), ('1.3', 'eDP 1.3'), ('1.4', 'eDP 1.4')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='processor',
            name='gpu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='processor',
            name='hdmi',
            field=models.CharField(choices=[('none', 'Not Supported'), ('1.4', 'HDMI 1.4'), ('2.0', 'HDMI 2.0'), ('2.1', 'HDMI 2.1')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='processor',
            name='lvds',
            field=models.CharField(choices=[('none', 'Not Supported'), ('single', 'Single-channel LVDS'), ('dual', 'Dual-channel LVDS')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='processor',
            name='sdio',
            field=models.BooleanField(default=False),
        ),
    ]
