# Generated by Django 6.0.1 on 2026-01-21 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_processor_arch_bits_remove_processor_cpu_arch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='back_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/back/'),
        ),
        migrations.AddField(
            model_name='product',
            name='front_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/front/'),
        ),
    ]
