# Generated by Django 4.2.24 on 2025-11-22 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_cores_product_image_product_ram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(choices=[('rockchip', 'Rockchip'), ('allwinner', 'Allwinner')], db_index=True, max_length=20)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('cpu_cores', models.PositiveIntegerField(blank=True, null=True)),
                ('cpu_arch', models.CharField(blank=True, max_length=100)),
                ('npu_tops', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_dram_gb', models.PositiveIntegerField(blank=True, null=True)),
                ('hdmi', models.BooleanField(default=False)),
                ('lvds', models.BooleanField(default=False)),
                ('edp', models.BooleanField(default=False)),
                ('dp', models.BooleanField(default=False)),
                ('mipi_dsi', models.BooleanField(default=False)),
                ('usb2_ports', models.PositiveIntegerField(blank=True, null=True)),
                ('usb3_ports', models.PositiveIntegerField(blank=True, null=True)),
                ('pcie_desc', models.CharField(blank=True, max_length=100)),
                ('ethernet_cap', models.CharField(blank=True, max_length=100)),
                ('sata', models.BooleanField(default=False)),
                ('sdio', models.BooleanField(default=True)),
                ('extra', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['vendor', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('short_tagline', models.CharField(blank=True, max_length=255)),
                ('dram_config', models.CharField(blank=True, max_length=150)),
                ('emmc_config', models.CharField(blank=True, max_length=150)),
                ('storage_slots', models.CharField(blank=True, max_length=200)),
                ('wifi', models.CharField(blank=True, max_length=150)),
                ('ethernet', models.CharField(blank=True, max_length=200)),
                ('video_connectors', models.CharField(blank=True, max_length=200)),
                ('expansion', models.CharField(blank=True, max_length=200)),
                ('gpio_headers', models.CharField(blank=True, max_length=200)),
                ('power_input', models.CharField(blank=True, max_length=150)),
                ('form_factor', models.CharField(blank=True, max_length=150)),
                ('additional_info', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='product.processor')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
