# Generated by Django 4.2.24 on 2025-11-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_vendor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processor',
            name='arch_bits',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processor',
            name='l1_cache_kb',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processor',
            name='l2_cache_kb',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processor',
            name='max_dram_gb',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processor',
            name='usb2_ports',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processor',
            name='usb3_ports',
            field=models.CharField(blank=True, null=True),
        ),
    ]
