# Generated by Django 4.2.24 on 2025-11-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_processor_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='processors/'),
        ),
        migrations.AddField(
            model_name='processor',
            name='arch_bits',
            field=models.PositiveSmallIntegerField(blank=True, help_text='32 or 64 bit CPU architecture', null=True),
        ),
        migrations.AddField(
            model_name='processor',
            name='gpu',
            field=models.CharField(blank=True, help_text='GPU model e.g. Mali-G610 MP4', max_length=100),
        ),
        migrations.AddField(
            model_name='processor',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload chip photo (.png or .jpg)', null=True, upload_to='processors/'),
        ),
        migrations.AddField(
            model_name='processor',
            name='l1_cache_kb',
            field=models.PositiveIntegerField(blank=True, help_text='Total L1 cache in KB', null=True),
        ),
        migrations.AddField(
            model_name='processor',
            name='l2_cache_kb',
            field=models.PositiveIntegerField(blank=True, help_text='Total L2 cache in KB', null=True),
        ),
        migrations.AlterField(
            model_name='processor',
            name='max_dram_gb',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum supported DRAM (GB)', null=True),
        ),
        migrations.AlterField(
            model_name='processor',
            name='npu_tops',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='NPU TOPS rating (e.g. 6.00)', max_digits=5, null=True),
        ),
    ]
