# Generated by Django 4.2.24 on 2025-11-29 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_processor_arch_bits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='vendors/banners/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='features',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_type',
            field=models.CharField(choices=[('hardware', 'Hardware'), ('software', 'Software')], default='hardware', max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
