# Generated by Django 4.2.24 on 2025-11-29 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_vendor_banner_image_vendor_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='features',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='vendor_type',
        ),
    ]
