# Generated by Django 6.0.1 on 2026-01-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_add_front_back_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ethernet_10_100',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ethernet_1g',
        ),
        migrations.AddField(
            model_name='product',
            name='ethernet_type',
            field=models.CharField(choices=[('NONE', 'No Ethernet'), ('10_100', '10/100 Mbps'), ('1G', '1 Gigabit'), ('DUAL_1G', 'Dual Gigabit')], default='NONE', max_length=20),
        ),
    ]
