# Generated by Django 6.0.1 on 2026-01-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_product_ethernet_10_100_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ethernet_type',
        ),
        migrations.AlterField(
            model_name='product',
            name='ethernet',
            field=models.CharField(choices=[('NONE', 'No Ethernet'), ('10_100', '10/100 Mbps'), ('1G', '1 Gigabit'), ('DUAL_1G', 'Dual Gigabit')], default='NONE', max_length=20),
        ),
    ]
